# Generated by Django 4.1.5 on 2023-02-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graphene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_x', models.TextField(default='')),
                ('size_y', models.TextField(default='')),
                ('pbc', models.TextField(blank=True, default='None')),
                ('cnt', models.TextField(blank=True, default='None')),
                ('hole', models.TextField(default='None')),
                ('radius', models.TextField()),
            ],
        ),
    ]
