# Generated by Django 4.1.6 on 2023-02-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dna',
            name='num',
            field=models.TextField(blank=True),
        ),
    ]
