# Generated by Django 4.1.6 on 2023-02-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dna', '0002_dna_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dna',
            name='num',
            field=models.IntegerField(blank=True),
        ),
    ]
